config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "bookings#index"

  resources :bookings
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    validates_presence_of :name
    validates_presence_of :service
    validates_presence_of :start_time

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    @bookings = Booking.where(start_time: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
    @user = current_user if user_signed_in?
  end

  def new
    @booking = Booking.new
  end

  def create
    @user = current_user
    @booking = @user.bookings.create(booking_params)
    redirect_to bookings_url
  end
  
  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end
  private 

  def booking_params
    params.require(:booking).permit(:name, :service, :date, :start_time)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
            controller.render(options.merge(formats: :html))
        rescue ActionView::MissingTemplate => e
           if get?
            raise e
           elsif has_errors? && default_action
            render rendering_options.merge(formats: :html, status: :unprocessable_entity)
           else
            redirect_to navigation_location
           end
        end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user_is_admin?
        if current_user && current_user.admin
            true
        else
            false
        end
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/index.html.erb
<h1>Bookings#index</h1>
<p>Find me in app/views/bookings/index.html.erb</p>

<h1>Calendar</h1>

<h3><%= link_to "make an appointment", new_booking_path %></h3>

<%= week_calendar do |date| %>
    <%= date %>
    <% @bookings.each do | booking | %>
        <% if date.strftime("%Y-%m-%d") == booking.start_time.strftime("%Y-%m-%d") %>
            <div>
                <%= booking.start_time.strftime("%H:%M") %>
                <% if booking.user == current_user || current_user_is_admin? %><br>
                    <%= booking.name %><br>
                    <%= booking.service %><br>
                    <%= link_to "View", booking_path(booking) %>
                <% end %>
            </div>
        <% end %>
    <% end %>
<% end %>

app/views/bookings/new.html.erb
<head>
    <title>New Booking</title>
</head>
<body>
    <%= form_for @booking do | form | %>
        <%= form.label :name %><br>
        <%= form.text_field :name %><br><br>
        <%= form.label :service %><br>
        <%= form.text_field :service %><br><br>
        <%= form.label :start_time %><br>
        <%= form.datetime_local_field :start_time %><br><br>

        <%= form.submit "Submit" %>
    <% end %>
        
</body>

app/views/bookings/show.html.erb
<%= @booking.start_time.strftime("%H:%M")%>
<br>
<%= @booking.name %>
<br>
<%= @booking.service %>
<br>
<% if @booking.user == current_user %>
    <%= link_to "Delete", @booking, method: :delete %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
    <ul>
        <% if current_user %>
            <li>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
            </li>
        <% else %>
            <li>
                <%= link_to "Sign up", new_user_registration_path %>
            </li>
            <li>
                <%= link_to "Sign in", new_user_session_path %>
            </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <header>
    <%= render "layouts/navbar" %>
  </header>
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>